### ISSUE TITLE
Ask Custom Column in wrapper

### ISSUE THREAD

**Issue by argotri** [qidaizhe11/element-table-wrapper#2]
hello @qidaizhe11  
i have try your wrapper to create pagination from element ui table wrapper that you create
i have a little problem
in my element ui table, i have custom column in my table
 ```javascript
<el-table-column label="Operation">
                      <template slot-scope="scope">
                        <el-button
                          size="mini"
                          @click="openModalEdit(scope.row)">Edit</el-button>

                        <el-button
                          v-show="scope.row.activated"
                          size="mini"
                          type="danger"
                          @click="disactivateUser(scope.row)">Nonaktifkan</el-button>
                        <el-button
                          v-show="!scope.row.activated"
                          size="mini"
                          type="success"
                          @click="disactivateUser(scope.row)">Aktifkan</el-button>

                      </template>
                    </el-table-column>
```
how i can create custom column like that using your wrapper  :octocat:  ? 

Thank you , your code is awasome

**Comment by qidaizhe11** [comment]
Didn't spare time to fix it quickly, sorry, busy working recently. It should be fiexed this weekend (not very easy to fix, since the source code of el-table became unfamilar to me already).

Maybe this project has follow this feature, I suppose, may it help, https://github.com/njleonzhang/vue-data-tables.

If not, i am afraid only this left i can remember https://github.com/vueComponent/ant-design, warning: it's not stable yet.

**Comment by argotri** [comment]
Cool ,thanks for suggestion >_<
